// ── SHARED INITIAL TASK DATA ─────────────────────────────────────────────────
// Lives in its own file so App.jsx only exports components (Fast Refresh rule)

export const INITIAL_TASK_DATA = {
  today: [
    { id: 94,   createdAt: '2026-03-08T10:00:00Z', title: 'Block time reports: Oct - current',            category: 'work', type: 'internal', est: '20m' },
    { id: 91,   createdAt: '2026-03-18T10:00:00Z', title: 'Bank recs Jan 2025',                           category: 'work', type: 'internal', est: '1h' },
    { id: 9,    createdAt: '2026-03-25T10:00:00Z', title: 'BO - OVERDUE',                                 category: 'work', type: 'internal', est: '30m' },
    { id: 1466, createdAt: '2026-04-01T10:00:00Z', title: 'Add Heather to GoWP',                          category: 'work', type: 'client',   est: '30m' },
    { id: 54,   createdAt: '2026-04-05T10:00:00Z', title: 'Off-board Sophos',                             category: 'work', type: 'client',   client: 'Sophos',       est: '30m' },
    { id: 26,   createdAt: '2026-04-01T10:00:00Z', title: 'Close Bulwark',                                category: 'work', type: 'client',   client: 'Bulwark',      est: '30m' },
    { id: 53,   createdAt: '2026-03-25T10:00:00Z', title: 'Off-board Josh Bean',                          category: 'work', type: 'client',   client: 'Josh Bean',    est: '30m' },
    { id: 1576, title: 'Send Price Increase Emails in Phases',         category: 'work', type: 'internal', est: '2h' },
    { id: 62,   createdAt: '2026-03-18T10:00:00Z', title: 'Kyle Largent: clean up ClickUp mess',          category: 'work', type: 'client',   client: 'Kyle Largent', est: '30m' },
    { id: 1490, title: "Hannah's hours fix",                           category: 'work', type: 'internal', est: '1h' },
    { id: 154,  title: 'Deckmasters Privacy Policy',                   category: 'work', type: 'client',   client: 'Deckmasters',  est: '45m' },
    { id: 10,   createdAt: '2026-02-25T10:00:00Z', title: 'Update open invoices',                         category: 'work', type: 'internal', est: '1h' },
    { id: 167,  title: "BurnBot: Review Alejandro's GA4 plugin setup", category: 'work', type: 'client',   client: 'BurnBot',      est: '1h' },
    { id: 1071, title: 'Call for Unitus statements',                   category: 'work', type: 'internal', est: '1h' },
    { id: 1075, title: 'Run Wednesday meeting through AI',             category: 'work', type: 'client',   est: '1h' },
    { id: 1236, title: 'Send Stellar J invoice - 1 year at $59',      category: 'work', type: 'client',   client: 'Stellar J',    est: '1h' },
    { id: 1239, title: 'Point Daniela site - email A record',         category: 'work', type: 'client',   est: '1h' },
    { id: 1007, title: 'Codefinity Lessons',                           category: 'personal', subTag: 'Hobbies', est: '1h',  recur: 'daily' },
    { id: 1560, title: 'Fix repository API issue',                     category: 'personal', subTag: 'Hobbies', est: '30m', due: '2026-04-09' },
  ],
  week: [
    { id: 51,   title: 'Cascade Tech: identify theme, coordinate GoWP update', category: 'work', type: 'client', client: 'Cascade Tech', assignee: 'Holly', est: '30m' },
    { id: 4,    title: 'MPC: Check block time; follow up with Julie on SOW',   category: 'work', type: 'client', client: 'MPC',          est: '15m' },
    { id: 25,   title: 'Pautzke issue',                                category: 'work', type: 'client',   client: 'Pautzke',      est: '30m' },
    { id: 1009, title: 'Send CFTH retainer and monthly plan invoice',  category: 'work', type: 'client',   client: 'CFTH',         est: '1h' },
    { id: 169,  title: 'Investigate connecting SalesAt Claude to Drive', category: 'work', type: 'internal', est: '45m' },
    { id: 11,   title: 'Investigate phishing/spam emails impersonating Abby', category: 'work', type: 'internal', est: '15m' },
    { id: 1728, title: 'Bank Recs Feb 2025',                           category: 'work', type: 'internal', est: '2h' },
    { id: 1729, title: 'Bank Recs March 2025',                         category: 'work', type: 'internal', est: '2h' },
    { id: 1973, title: 'What is this MPC ClickUp list?',               category: 'work', type: 'client',   client: 'MPC',          est: '30m' },
    { id: 6,    title: 'Cascade Tech: Add CAPTCHA to forms',           category: 'work', type: 'client',   client: 'Cascade Tech', est: '20m' },
    { id: 30,   title: 'Cascade Tech forms cleanup',                   category: 'work', type: 'client',   client: 'Cascade Tech', est: '30m' },
    { id: 61,   title: 'Clean out old clients in ClickUp',             category: 'work', type: 'internal', est: '30m' },
    { id: 170,  title: 'Update build instructions: Termageddon for GA4', category: 'work', type: 'internal', est: '30m' },
  ],
  nextweek: [
    { id: 55,   title: "Clean up ClickUp for Sarah's Garden",          category: 'work', type: 'client',   client: "Sarah's Garden", est: '30m' },
    { id: 1498, title: 'HH Wood Recycler Pricing Changes eff. 4/13',  category: 'work', type: 'client',   client: 'H & H',          est: '30m', due: '2026-04-14' },
    { id: 114,  title: 'Add employee annual reviews to calendar',      category: 'work', type: 'internal', est: '20m' },
    { id: 101,  title: 'Registered agents: Nevada + Missouri',         category: 'work', type: 'internal', est: '30m' },
    { id: 1378, title: 'March Invoices',                               category: 'work', type: 'internal', est: '1h' },
    { id: 57,   title: 'GoDaddy for Abby: spykerimaging hosting',     category: 'work', type: 'internal', assignee: 'Abby', est: '20m' },
    { id: 82,   title: 'Investigate clients on hosting without maintenance', category: 'work', type: 'client', est: '45m' },
    { id: 143,  title: 'Look into certifications',                     category: 'personal', subTag: 'Miscellaneous', est: '30m' },
    { id: 1794, title: 'Update Personal Resume',                       category: 'personal', subTag: 'Miscellaneous', est: '30m' },
    { id: 64,   title: 'PDF for Calli',                                category: 'personal', subTag: 'Family',        est: '30m' },
  ],
  backlog: [
    { id: 80,  title: 'Plan for notifying hosting-only clients',               category: 'work', type: 'client',   est: '30m' },
    { id: 81,  title: 'Email series for non-maintenance clients',              category: 'work', type: 'client',   est: '15m' },
    { id: 84,  title: 'PCI Compliance (DSS 4.0): Stripe, Shopify review',     category: 'work', type: 'client',   est: '30m' },
    { id: 85,  title: 'PCI: Review Connections Cafe, Alder Creek, Premier',   category: 'work', type: 'client',   est: '30m' },
    { id: 90,  title: 'Go through recurring invoices for tax issues',          category: 'work', type: 'internal', est: '1h' },
    { id: 92,  title: 'Bank rec January 2026',                                 category: 'work', type: 'internal', est: '1h' },
    { id: 93,  title: 'Bank rec February 2026',                                category: 'work', type: 'internal', est: '1h' },
    { id: 95,  title: 'New DOR apportionment process',                         category: 'work', type: 'internal', est: '30m' },
    { id: 96,  title: 'Oregon DOR 2022: payroll done incorrectly',             category: 'work', type: 'internal', est: '20m' },
    { id: 97,  title: 'WA DOR follow-up on apportionments 2025',              category: 'work', type: 'internal', est: '15m' },
    { id: 100, title: 'NWMC liability insurance: find / change carrier',       category: 'work', type: 'internal', est: '30m' },
    { id: 102, title: 'NWMC codes & important info: save to Drive',           category: 'work', type: 'internal', est: '30m' },
    { id: 103, title: 'Hosting & maintenance list: clean up Airtable',        category: 'work', type: 'internal', est: '30m' },
    { id: 104, title: 'GSuite: clean up users',                                category: 'work', type: 'internal', est: '30m' },
    { id: 106, title: '2FA: shared email/alias for team access',              category: 'work', type: 'internal', est: '15m' },
    { id: 107, title: 'Company intranet/dashboard setup',                      category: 'work', type: 'internal', est: '1h' },
    { id: 110, title: 'Company SLA & proposal documents',                     category: 'work', type: 'internal', est: '30m' },
    { id: 112, title: 'Company SOPs',                                          category: 'work', type: 'internal', est: '30m' },
    { id: 113, title: 'Hiring process documentation',                          category: 'work', type: 'internal', est: '30m' },
    { id: 115, title: 'ClickUp full cleanup',                                  category: 'work', type: 'internal', est: '30m' },
    { id: 120, title: 'TARDIS / Personal AI project',                          category: 'work', type: 'internal', est: '30m' },
    { id: 121, title: 'Client dashboard (AI project)',                         category: 'work', type: 'internal', est: '30m' },
    { id: 122, title: 'Triage email automation (AI project)',                  category: 'work', type: 'internal', est: '15m' },
    { id: 123, title: 'Company wiki (AI project)',                             category: 'work', type: 'internal', est: '30m' },
    { id: 36,  title: 'Fix ImprovMX: help@ alias',                            category: 'work', type: 'internal', est: '1h' },
    { id: 37,  title: 'Troubleshoot SupportBee forwarding to Holly',          category: 'work', type: 'internal', est: '15m' },
    { id: 130, title: "Chris' 2021-2023 taxes",                                category: 'personal', subTag: 'Finance',   est: '2h' },
    { id: 131, title: 'Our 2024 taxes',                                        category: 'personal', subTag: 'Finance',   est: '2h' },
    { id: 132, title: '2025 taxes',                                            category: 'personal', subTag: 'Finance',   est: '2h' },
    { id: 133, title: 'Update debt spreadsheet to current',                    category: 'personal', subTag: 'Finance',   est: '30m' },
    { id: 134, title: 'Sew bathroom curtains',                                 category: 'personal', subTag: 'Household', est: '2h' },
    { id: 135, title: 'Pick paint for bathroom',                               category: 'personal', subTag: 'Household', est: '2h' },
    { id: 136, title: 'Paint bathroom',                                        category: 'personal', subTag: 'Household', est: '2h' },
    { id: 138, title: 'Clean up room and organize',                            category: 'personal', subTag: 'Household', est: '45m' },
    { id: 140, title: "Hubby's sweater",                                       category: 'personal', subTag: 'Hobbies',   est: '30m' },
    { id: 141, title: 'Sew jumpsuit',                                          category: 'personal', subTag: 'Hobbies',   est: '2h' },
    { id: 142, title: 'Order maverick quillow fabric (~$60)',                  category: 'personal', subTag: 'Hobbies',   est: '15m' },
  ],
  waiting: [
    { id: 1006, title: 'Danielle at Bloom Services: broken Yoast plugin',     category: 'work', type: 'client', client: 'Bloom Services', est: '30m', details: "Waiting on Danielle's response." },
    { id: 1007, title: 'Poolmasters: waiting on Eric for Mailchimp',          category: 'work', type: 'client', client: 'Poolmasters',    est: '30m' },
    { id: 1008, title: 'Send Poolmasters invoice',                             category: 'work', type: 'client', client: 'Poolmasters',    est: '1h',  details: 'Waiting on Eric approval.' },
    { id: 20,   title: 'Schedule call with Scott at CCSI re: security scan',  category: 'work', type: 'client', client: 'CCSI',           est: '15m', details: 'Include Abby.' },
    { id: 171,  title: 'BurnBot: Follow up on reverse proxy and DNS',         category: 'work', type: 'client', client: 'BurnBot',        est: '15m', details: 'Waiting on Abby.' },
    { id: 56,   title: "Check hosting & maintenance for Sarah's Garden",      category: 'work', type: 'client', client: "Sarah's Garden", est: '15m', due: '2026-04-15', details: 'Invoice sends mid April.' },
    { id: 1003, title: 'Send SOW to CFTH (Charlene) for branding retainer',  category: 'work', type: 'client', client: 'CFTH',           est: '20m' },
    { id: 22,   title: 'CCSI: Check if they finished their updates',          category: 'work', type: 'client', client: 'CCSI',           est: '30m' },
    { id: 1057, title: 'Stellar J - Decision needed for Staging Site',        category: 'work', type: 'client', client: 'Stellar J',      est: '15m', details: 'Waiting on Stellar J.' },
    { id: 1631, title: 'Payroll',                                              category: 'work', type: 'internal', est: '2h', recur: 'weekly' },
  ],
  delegate:  [],
  completed: [],
}
